### ISSUE TITLE
Error when registering with wrong authorisation code

### ISSUE THREAD

**Issue by nico-m-dev** [ron4mac/joomla_plg_regauth#1]
Hi, when i try to register with a wrong authorisation code i don't get the message but an error:
1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 3

**Comment by ron4mac** [comment]
I can not duplicate your result. The plugin does no direct database access. Perhaps there is a fault with some conflicting plugin?
Can you provide more information or a link to the site?

**Comment by nico-m-dev** [comment]
Hi, sorry for the late response. I've been busy lately.
I was thinking it maybe conflicted with my Awo Email login plugin, but disabeling this plugin didn't fix the error. Could it be because i have an adminexhile?
Yeah, it's probably some plugin i installed. i'm not a pro, more of a hobbyist

**Comment by ron4mac** [comment]
The issue has been discovered and corrected.
